### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by ChenZhu9** [sharif-apu/BJDD_CVPR21#8]
1. When I use the inference, I need to change "binningFactor" in config.json to "binnigFactor" otherwise it will throw error.
2. line 83 in processDataset.py should be changed to "elif self.gridSze == 2:"

**Comment by sharif-apu** [comment]
Can you please explain your points? I could not figure it out.

**Comment by ChenZhu9** [comment]
1. I clone the code, download the pre-trained model and run `python3.8 main.py -i -s testingImages/ -d output/ -ns=1`, the output is:
```
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    BJDD(config).modelInference(testImagesPath=options.sourceDir, outputDir=options.resultDir, noiseSet=noiseSigmaSet)
  File "/BJDD_CVPR21/mainModule/BJDD.py", line 47, in __init__
    self.binnigFactor = int(config['binnigFactor'])
KeyError: 'binnigFactor' 
```
I need to change line 18 in [config.json](https://github.com/sharif-apu/BJDD_CVPR21/blob/main/mainModule/config.json) from `"binningFactor": 2,` to `"binnigFactor": 2,`  to avoid this error

2. I want to change the order of Bayer filter, like from RGGB to GRBG, so i modify the function bayerSampler() in [sampler.py](https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/sampler.py), but when I run `python main.py -ds -s /path/to/GTimages/ -d /path/to/saveSamples/ -g 2 -n 10000`, the output image is all black. This is because in line 82-86 in [processDataset.py](https://github.com/sharif-apu/BJDD_CVPR21/blob/main/dataTools/processDataset.py)
```
                if self.gridSze == 1:
                    image = bayerSampler(image)
                if self.gridSze == 2:
                    image = quadBayerSampler(image)
                else:
                    image = dynamicBayerSampler(image,self.gridSze)
```
When the gridSze=1, the image is actually sampled twice, by bayerSampler() and dynamicBayerSampler(), which will also cause extra calculation when using the original bayerSampler.

**Comment by ChenZhu9** [comment]
> Can you please explain your points? I could not figure it out.
